apiVersion: v1
   kind: ConfigMap
   metadata:
     name: nginx-config
     namespace: default
   data:
     index.html: |
       <html>
       <body>
       <h1>Hello from nginx-ingress</h1>
       </body>
       </html>
